server:
  port: ${SERVER_PORT:19001}

management:
  server:
    port: 18001
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: "*"
  tracing:
    enabled: true
    sampling:
      probability: 1.0
  prometheus:
    metrics:
      export:
        enabled: true
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

spring:
  application:
    name: common-function
  datasource:
    url: jdbc:postgresql://localhost:5432/common-db
    username: username
    password: password
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      database: ${REDIS_DATABASE:0}

kafka:
  bootstrap-servers: ${KAFKA_SERVER:localhost:9092}
  producers:
    test:
      topic: ${KAFKA_PRODUCER_TEST_TOPIC:test1}
  consumers:
    test:
      topic: ${KAFKA_CONSUMER_TEST_TOPIC:test1}
      group-id: ${KAFKA_CONSUMER_TEST_GROUP_ID:test-group-id}
      auto-offset-reset: ${KAFKA_CONSUMER_TEST_OFFSET_RESET:earliest}
