server:
  port: ${SERVER_PORT:19001}

spring:
  application:
    name: common-function
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      database: ${REDIS_DATABASE:0}

kafka:
  bootstrap-servers: ${KAFKA_SERVER:localhost:9092}
  producers:
    test:
      topic: ${KAFKA_PRODUCER_TEST_TOPIC:test1}
  consumers:
    test:
      topic: ${KAFKA_CONSUMER_TEST_TOPIC:test1}
      group-id: ${KAFKA_CONSUMER_TEST_GROUP_ID:test-group-id}
      auto-offset-reset: ${KAFKA_CONSUMER_TEST_OFFSET_RESET:earliest}